dask: Deprecate `close`
NCAS-CMS/cf-python pull request #504
Opened 2022-11-22 13:35 UTC by davidhassell

Deprecates `close` methods, and removes the corresponding tests.

2022-12-05 19:14 UTC, sadielbartholomew reviewed
Close, but no cigar! :laughing: Feel free to apply the recurrent change suggested yourself rather than via my 'suggestion' set if that's more convenient, but I've made them as suggestions in case that is simplest.

Is there a location we can put some brief testing on deprecated keywords such as this, since nothing failed in the test suite despite the consistent invalid keyword argument here, and it would be good to catch basic issues like that?

2022-12-05 19:14 UTC, sadielbartholomew commented on cf/constructs.py
> +            remove_at="5.0.0",
```suggestion
            removed_at="5.0.0",
```

2022-12-05 19:14 UTC, sadielbartholomew commented on cf/coordinatereference.py
> +            remove_at="5.0.0",
```suggestion
            removed_at="5.0.0",
```

2022-12-05 19:14 UTC, sadielbartholomew commented on cf/domain.py
> +            remove_at="5.0.0",
```suggestion
            removed_at="5.0.0",
```

2022-12-05 19:14 UTC, sadielbartholomew commented on cf/field.py
> +            remove_at="5.0.0",
```suggestion
            removed_at="5.0.0",
```

2022-12-05 19:14 UTC, sadielbartholomew commented on cf/mixin/propertiesdata.py
> +            remove_at="5.0.0",
```suggestion
            removed_at="5.0.0",
```

2022-12-05 19:14 UTC, sadielbartholomew commented on cf/mixin/propertiesdatabounds.py
> +            remove_at="5.0.0",
```suggestion
            removed_at="5.0.0",
```

2022-12-05 19:14 UTC, sadielbartholomew requested changes
[Intended to set this as my judgement in the review I just submitted...]

2022-12-06 09:22 UTC, davidhassell commented
> Is there a location we can put some brief testing on deprecated keywords such as this, since nothing failed in the test suite despite the consistent invalid keyword argument here, and it would be good to catch basic issues like that?

Hi Sadie, good idea. Not yet - I suppose a new file `test_deprecated.py` might be a good place to put them, from where they can easily be deleted once the `removed_at` version is reached.

2022-12-06 12:50 UTC, sadielbartholomew commented
> I suppose a new file test_deprecated.py might be a good place to put them, from where they can easily be deleted once the removed_at version is reached.

Sounds like a good plan to me. Shall we bump it to a new issue, since the Dask migration takes priority I am sure?

2022-12-06 13:08 UTC, sadielbartholomew approved these changes
Feedback all addressed. All good now, please merge.

2022-12-06 13:10 UTC, merged