Fixed issues with captions of certain tutorials
NCAS-CMS/cf-python pull request #533
Opened 2022-12-19 18:28 UTC by bewithankit

Fixes #529

2022-12-19 19:25 UTC, davidhassell requested changes
Hi Ankit - thank you for spotting these defects and fixing them!

I've made a few suggestions for you to consider - the main thing being the ordinal numbers were out by 1 :)

2022-12-19 19:25 UTC, davidhassell commented on docs/source/tutorial.rst
> +     :caption: *Create subspace by selecting the 1st, 2nd, 4th and 6th elements of the 'X' axis by creating an envelope of these elements and mising data within the envelope wherever needed.*
```suggestion
     :caption: *Create a subspace by selecting the 2nd, 3rd, 5th and 7th elements of the 'X' axis by creating an envelope of these elements with missing data within the envelope wherever needed.*
```

2022-12-19 19:25 UTC, davidhassell commented on docs/source/tutorial.rst
> +     :caption: *Create subspace by selecting the 1st, 2nd, 4th and 6th elements of the 'X' axis with domain encompassing that of the original field contruct and mising data within the domain wherever
```suggestion
     :caption: *Create a subspace by selecting the 2nd, 3rd, 5th and 7th elements of the 'X' axis with domain encompassing that of the original field construct with missing data within the domain wherever needed.*
```

2022-12-19 19:25 UTC, davidhassell commented on docs/source/tutorial.rst
> +   :caption: *Create subspace whose domain spans latitudes within the range of 51 to 53 degrees north, with the other domain axes remaining unchanged.*
```suggestion
   :caption: *Create a subspace whose domain spans latitudes within the range of 51 to 53 degrees north, with the other domain axes remaining unchanged.*
```

2022-12-19 19:25 UTC, davidhassell commented on docs/source/tutorial.rst
> +   :caption: *An example evaluating compound query operation involving a greater than or equal to 3 and a strictly less than 5 condition.*
```suggestion
   :caption: *An example evaluating a compound query operation involving a greater than or equal to 3 condition and a strictly less than 5 condition.*
```

2022-12-19 19:25 UTC, davidhassell commented on docs/source/tutorial.rst
> +     :caption: *Create subspace by compressing the domain spanning the 1st, 2nd, 4th and 6th elements of the 'X' axis, with the other domain axes remaining unchanged.*
```suggestion
     :caption: *Create a subspace by compressing the domain spanning the 2nd, 3rd, 5th and 7th elements of the 'X' axis, with the other domain axes remaining unchanged.*
```

2022-12-19 19:25 UTC, davidhassell commented on docs/source/tutorial.rst
> +   :caption: *Create subspaces in different ways based on the time dimension by selecting a particular date and using date-time and its queries.*
```suggestion
   :caption: *Create subspaces in different ways based on the time dimension by selecting a particular date and using date-time and date-time queries.*
```

2022-12-19 19:25 UTC, davidhassell commented on docs/source/tutorial.rst
> +   :caption: *An example evaluating a strictly less than 3 query operation.*
```suggestion
   :caption: *An example evaluating a strictly less than 3 query condition.*
```

2022-12-20 09:58 UTC, bewithankit commented
Ah, the ordinal numbers! Thank you David!

2022-12-20 13:46 UTC, merged