Added Cheat Sheet
NCAS-CMS/cf-python pull request #656
Opened 2023-05-18 11:57 UTC by bewithankit

Resolves #591.

2023-05-18 15:02 UTC, davidhassell requested changes
Looks great. Some suggestions ...

2023-05-18 15:02 UTC, davidhassell commented on docs/source/cheat_sheet.rst
> +|                          |       >>> ensemble = cf.aggregate(f, dimension=("realization",), relaxed_identities=True)[0]                                                                         |
```suggestion
```
As discussed offline, we'll remove this for now, and decide how best to represent aggregation later.

2023-05-18 15:02 UTC, davidhassell commented on docs/source/cheat_sheet.rst
> +|        **Install**       | *Install cf-python as root, with any missing dependencies, and the cf-plot visualisation package using pip:*                                                         |
```suggestion
|        **Install**       | *Install cf-python, including any required dependencies, and the cf-plot visualisation package using pip:*                                                         |
```

2023-05-18 15:02 UTC, davidhassell commented on docs/source/cheat_sheet.rst
> +|                          |                                                                                                                                                                      |
```suggestion
```

2023-05-18 15:13 UTC, sadielbartholomew commented
I'm aware this is still in draft form, but from a quick peek it is looking fantastic. If you'd like a second review (though probably not necessary) feel free to assign me when it is ready.

2023-05-18 15:50 UTC, bewithankit commented
Thanks for the suggestions David! 
Sadie, I'll add a few things and request a review from you!

2023-05-19 10:50 UTC, bewithankit commented
Hi @sadielbartholomew, I have marked it ready for review. You could either generate the documentation on your system or just head to https://github.com/bewithankit/cf-python/blob/cheatsheet/docs/source/cheat_sheet.rst where it renders properly!

2023-05-22 16:07 UTC, sadielbartholomew approved these changes
I've raised several minor comments, but overall this is looking excellent. Let me know what you think, but this close to merge IMO...

2023-05-23 14:43 UTC, sadielbartholomew commented
Thanks for addressing the feedback, Ankit. @davidhassell are you happy with the present state, in which case I think we can merge?

2023-05-23 15:38 UTC, bewithankit commented
Hi Sadie, thanks again for the suggestions. As the Cheat Sheet will be an addition to the sidebar menu, all the pages will need to be regenerated again. I think David said we'll add it in the next release as it'll be easier that way!

2023-05-23 16:02 UTC, sadielbartholomew commented
Sounds good. I'm looking forward to seeing it in the documentation. Thanks Ankit.

2023-05-30 10:51 UTC, bewithankit commented on docs/source/cheat_sheet.rst
> +|                             **Accessing constructs**                             | *Select constructs by identity:*
Thanks for the suggestion David. I thought users might not know all the metadata constructs so thought of putting the `constructs` container! I have done the changes, let me know if those are correct, thanks!

2023-05-30 10:52 UTC, bewithankit commented on docs/source/cheat_sheet.rst
> +|                                  **Regridding**                                  | **Spherical regridding for regridding data between domains with spherical coordinate systems:**
Hi David, I didn't get this!

2023-05-30 11:09 UTC, davidhassell commented on docs/source/cheat_sheet.rst
> +|                                  **Regridding**                                  | **Spherical regridding for regridding data between domains with spherical coordinate systems:**
Hi ANkit, sorry, it did get a bit confusing! I'm suggesting replacing `**Spherical regridding for regridding data between domains with spherical coordinate systems:**` with 
```
**Regridding in spherical polar coordinates**
```

2023-06-05 09:46 UTC, davidhassell approved these changes
Great. One minor suggestion - merge at will.

2023-06-05 09:46 UTC, davidhassell commented on docs/source/cheat_sheet.rst
> +|                                                                                  | **Selecting field:**
```suggestion
|                                                                                  | **Selecting fields:**                                                                                                                                                            |
```

2023-06-05 10:07 UTC, bewithankit commented
Hi David, just wanted to confirm if I should merge it now or do it in the next release as we had talked?

2023-06-05 10:22 UTC, davidhassell commented
Hi - I think that you can merge it now, it just won't show up till the next release when we rebuild the docs (well the it will appear in the side bar of index.html, but won't work - that's OK for a few days)

2023-06-05 10:25 UTC, merged