Get core Dask functionality from `cfdm`
NCAS-CMS/cf-python pull request #836
Opened 2024-12-05 11:38 UTC by davidhassell

No associated issue.

Remove core Dask functionality, importing it from `cfdm` instead.

Requires https://github.com/NCAS-CMS/cfdm/pull/312 from `cfdm`.

Aims to not change the API, other than as required by the new `cfdm`.

2025-01-08 00:50 UTC, sadielbartholomew requested changes
Looks good overall except for the case of the updated API for the binary operations stemming from a change to `_binary_operation` (which may have been deliberate but I suspect not) - see my inline comments regarding that which summarise my thoughts.

Otherwise just the usual minor comments. So happy to approve once we've considered/discussed the above issue. Thanks for your patience on this review.

2025-01-08 00:50 UTC, sadielbartholomew commented on cf/data/data.py
> +    # These must constants must have values 2**N (N>=1), except for
```suggestion
    # These constants must have values 2**N (N>=1), except for
```

2025-01-08 00:50 UTC, sadielbartholomew commented on cf/data/data.py
> +         [ --   --]s
```suggestion
         [ --   --]
```

(Looks like an accidental keystroke or similar...)

2025-01-08 00:50 UTC, sadielbartholomew commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
As per my other comments about this method's API, but to point out a relevant part of code, I recommend we revert (i.e. leave - but revert relative to this PR branch) this to a regular/instance method i.e:

```suggestion
    def _binary_operation(self, other, method):
```

so we don't have the bad API of the data in question needing to be provided as an argument when the object the method operates on already defines it, i.e. `Data1._binary_operation(Data1, Data2, method)`.

Then of course the rest of the method will need some updates to account for that new signature, which I won't raise as suggestions.

2025-01-08 00:50 UTC, sadielbartholomew commented on cf/data/data.py
> +        return self._binary_operation(self, other, "__add__")
:grimacing: Not nice, in my opinion.

2025-01-08 00:50 UTC, sadielbartholomew commented on cf/data/data.py
> +        therefore allow cyclic slicing). The set contains a subset of
```suggestion
        therefore allows cyclic slicing). The set contains a subset of
```

2025-01-08 09:46 UTC, davidhassell commented on cf/field.py
> +        )
I'm trying to remember why I thought is was necessary to make `_binary_operation` a class method. I'll get back to you ...

2025-01-08 10:19 UTC, davidhassell commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
OK - I've remembered! The reason for making it a class method in `cfdm` was to allow us to use more nicely use `super()` in `cf.Data._binary_operation`, at line https://github.com/davidhassell/cf-python/blob/dask-in-cfdm/cf/data/data.py#L2452:
```python
        d = super()._binary_operation(data0, other, method)
```
Does that make sense?

The lines that follow are a bit nasty:
```python
        d.override_units(new_Units, inplace=True)  # This line is nice :)
        if inplace:
            data.__dict__ = d.__dict__  # Yuck :(
        else:
            data = d
```
Can you think of any improvements?

2025-01-08 12:06 UTC, sadielbartholomew commented on cf/field.py
> +        )
No worries - the more reviewing I did the more I changed my mind and thought it might  indeed be deliberate, to update my comment above!

2025-01-08 13:10 UTC, sadielbartholomew commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
OK, had a little explore. I think the way I would do it is to revert `_binary_operation` to be an instance method in *both* `cfdm` and `cf`, with appropriate tweaks to the code in those methods in these PR branches to get that working. Then `super()` should work fine without `data0` needed as an argument.

Then to avoid the `__dict__` copying, avoiding also a `deepcopy` which is obviously a way to do that but very non-performant, maybe we could have a new keyword to the `cfdm` `_binary_operation` called `asdict` or similar (that's what I've used in my `diff`s below, at least) which returns only the resulting `__dict__`, and make use of that. Still does the same as the line you mark 'yuck', but obscures the yuckiness at least?

There's a suggestion to discuss as a starting point, at least. As follows are the `diff`s from my investigative changes - I've run the `test_Data` in each case and they pass, though to get the full test suites to run some tweaks may need to be propagated e.g. to the mixins...

2025-01-08 13:15 UTC, sadielbartholomew commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
Changes made in line with the above as a suggestion, using both branches together as per the review of this PR.

### cfdm branch `diff` (PR https://github.com/NCAS-CMS/cfdm/pull/312)

```diff
diff --git a/cfdm/data/data.py b/cfdm/data/data.py
index 49aa052b8..207c559ef 100644
--- a/cfdm/data/data.py
+++ b/cfdm/data/data.py
@@ -1102,7 +1102,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__eq__")
+        return self._binary_operation(other, "__eq__")
 
     def __ne__(self, other):
         """The rich comparison operator ``!=``
@@ -1112,7 +1112,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__ne__")
+        return self._binary_operation(other, "__ne__")
 
     def __ge__(self, other):
         """The rich comparison operator ``>=``
@@ -1122,7 +1122,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__ge__")
+        return self._binary_operation(other, "__ge__")
 
     def __gt__(self, other):
         """The rich comparison operator ``>``
@@ -1132,7 +1132,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__gt__")
+        return self._binary_operation(other, "__gt__")
 
     def __le__(self, other):
         """The rich comparison operator ``<=``
@@ -1142,7 +1142,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__le__")
+        return self._binary_operation(other, "__le__")
 
     def __lt__(self, other):
         """The rich comparison operator ``<``
@@ -1152,7 +1152,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__lt__")
+        return self._binary_operation(other, "__lt__")
 
     def __and__(self, other):
         """The binary bitwise operation ``&``
@@ -1162,7 +1162,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__and__")
+        return self._binary_operation(other, "__and__")
 
     def __iand__(self, other):
         """The augmented bitwise assignment ``&=``
@@ -1172,7 +1172,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__iand__")
+        return self._binary_operation(other, "__iand__")
 
     def __rand__(self, other):
         """The binary bitwise operation ``&`` with reflected operands.
@@ -1182,7 +1182,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__rand__")
+        return self._binary_operation(other, "__rand__")
 
     def __or__(self, other):
         """The binary bitwise operation ``|``
@@ -1192,7 +1192,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__or__")
+        return self._binary_operation(other, "__or__")
 
     def __ior__(self, other):
         """The augmented bitwise assignment ``|=``
@@ -1202,7 +1202,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__ior__")
+        return self._binary_operation(other, "__ior__")
 
     def __ror__(self, other):
         """The binary bitwise operation ``|`` with reflected operands.
@@ -1212,7 +1212,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__ror__")
+        return self._binary_operation(other, "__ror__")
 
     def __xor__(self, other):
         """The binary bitwise operation ``^``
@@ -1222,7 +1222,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__xor__")
+        return self._binary_operation(other, "__xor__")
 
     def __ixor__(self, other):
         """The augmented bitwise assignment ``^=``
@@ -1232,7 +1232,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, other, "__ixor__")
+        return self._binary_operation(other, "__ixor__")
 
     def __rxor__(self, other):
         """The binary bitwise operation ``^`` with reflected operands.
@@ -1240,7 +1240,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         x.__rxor__(y) <==> y^x
 
         """
-        return self._binary_operation(self, other, "__rxor__")
+        return self._binary_operation(other, "__rxor__")
 
     def __lshift__(self, y):
         """The binary bitwise operation ``<<``
@@ -1250,7 +1250,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, y, "__lshift__")
+        return self._binary_operation(y, "__lshift__")
 
     def __ilshift__(self, y):
         """The augmented bitwise assignment ``<<=``
@@ -1258,7 +1258,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         x.__ilshift__(y) <==> x<<=y
 
         """
-        return self._binary_operation(self, y, "__ilshift__")
+        return self._binary_operation(y, "__ilshift__")
 
     def __rlshift__(self, y):
         """The binary bitwise operation ``<<`` with reflected operands.
@@ -1268,7 +1268,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, y, "__rlshift__")
+        return self._binary_operation(y, "__rlshift__")
 
     def __rshift__(self, y):
         """The binary bitwise operation ``>>``
@@ -1276,7 +1276,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         x.__lshift__(y) <==> x>>y
 
         """
-        return self._binary_operation(self, y, "__rshift__")
+        return self._binary_operation(y, "__rshift__")
 
     def __irshift__(self, y):
         """The augmented bitwise assignment ``>>=``
@@ -1286,7 +1286,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, y, "__irshift__")
+        return self._binary_operation(y, "__irshift__")
 
     def __rrshift__(self, y):
         """The binary bitwise operation ``>>`` with reflected operands.
@@ -1296,7 +1296,7 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
         .. versionadded:: (cfdm) NEXTVERSION
 
         """
-        return self._binary_operation(self, y, "__rrshift__")
+        return self._binary_operation(y, "__rrshift__")
 
     def __abs__(self):
         """The unary arithmetic operation ``abs``
@@ -1544,8 +1544,8 @@ class Data(Container, NetCDFHDF5, Files, core.Data):
     def _axes(self, value):
         self._set_component("axes", tuple(value), copy=False)
 
-    @classmethod
-    def _binary_operation(cls, data, other, method):
+    #@classmethod
+    def _binary_operation(self, other, method, asdict=False):
         """Binary arithmetic and comparison operations.
 
         It is called by the binary (i.e. two operands) arithmetic and
@@ -1587,18 +1587,20 @@ class Data(Container, NetCDFHDF5,  [...]

2025-01-08 13:17 UTC, sadielbartholomew commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
OK on second thought obscuring the yuckiness is probably even worse, so I might rethink that `__dict__` bit. But as for the main issue in my mind about the API, it seems like it is possible to use normal instance methods for `_binary_operation` as per the `diff`s - unless I am missing something?

2025-01-08 13:29 UTC, davidhassell commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
Th thing is we have mucked with units in `Data._combined_units`, and are no longer operating on `self`. Therefore we can only get at the `super` functionality (as far as know) if it is a class method.

This is where the subsequent nastiness comes from - hacking the result back into `self.__dict__`.

2025-01-08 13:32 UTC, davidhassell commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
Anyway, I remember now that this was definitely the reason I changed it to a class method. If we can get at the `super` functionality without it being a class method, that would be great :)

2025-01-08 14:36 UTC, sadielbartholomew commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
OK, I see - thanks for the further clarification. Having a further probe to see if I can think of a way around it. Thanks for your patience.

2025-01-08 15:38 UTC, sadielbartholomew commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
(Discussed via video call - it is indeed quite difficult to avoid using a class method so we've agreed having a comment explaining this is a sufficient solution, and we can always add a follow-on issue to look into refactoring `_combined_units` to see if we can avoid updating `self` since it is that which results in the need for the class method.)

2025-01-10 08:37 UTC, davidhassell commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
Hi Sadie - now that we've put this comment into the cfdm code, to cover the @classmethod question: https://github.com/NCAS-CMS/cfdm/pull/312#issuecomment-2579605122, are there any other outstanding issues here? (None I could see, but just checking!)

2025-01-15 16:54 UTC, sadielbartholomew commented on cf/data/data.py
> +        return self._binary_operation(self, other, "__add__")
Discussed offline, so marking as resolved.

2025-01-15 17:02 UTC, sadielbartholomew commented on cf/data/data.py
> +    def _binary_operation(cls, data, other, method):
Yes, all good now - so marking as resolved (sorry this comment got swamped over in my GitHub notifications). Nearly there with a final sanity check then will re-review to approve...

2025-01-15 17:25 UTC, sadielbartholomew approved these changes
A few minor comments left to address, some newly-introduced, but then I am happy, so please merge :slightly_smiling_face:

2025-01-15 17:25 UTC, sadielbartholomew commented on Changelog.rst
> +* Changed dependency: ``dask>=2024.6.0,<=2024.7.1``
Just to check this less than equal to `.1` is correct since the commit message states `dask<=2024.7.2`? Don't want to get the wrong pin...

2025-01-15 17:25 UTC, sadielbartholomew commented on cf/__init__.py
> +# Check the version of numpy
```suggestion
```

(Dask here, as per the comment above)

2025-01-15 17:25 UTC, sadielbartholomew commented on Changelog.rst
> +  (https://github.com/NCAS-CMS/cf-python/pull/836)
```suggestion
```

The new Changelog entry is now a duplicate - you'd already added one. So we should ditch one of them. For the record I prefer this message but the link to the Issue as per above, but removing either is fine.

2025-01-15 17:28 UTC, davidhassell commented on Changelog.rst
> +* Changed dependency: ``dask>=2024.6.0,<=2024.7.1``
`1` is correct.

2025-01-15 17:31 UTC, merged